version: "3.2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    restart: unless-stopped
    command: elasticsearch
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    environment:
      - MAX_LOCKED_MEMORY=unlimited

