version: "3.4"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    restart: unless-stopped
    command: elasticsearch
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - MAX_LOCKED_MEMORY=unlimited

  starchat:
    image: getjenny/jre:8
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ["/starchat/scripts/utils/wait-for-it.sh", "getjenny-es:9200",
              "-t", "15",
              "--", "/starchat/bin/starchat"]
    volumes:
      - ./starchat:/starchat
    ports:
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:8443:8443"
    links:
      - "elasticsearch:getjenny-es"
